name: Build Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add additional steps to build your Ruby application using Docker BuildKit and build-push-action
      # ...
- name: Enable Docker BuildKit
  run: |
    echo '{"features": {"buildkit": true}}' | sudo tee /etc/docker/daemon.json
    sudo service docker restart
- name: Build and push Docker image
  uses: docker/build-push-action@v2
  with:
    context: .
    file: Dockerfile
    push: true
    tags: camilla-m/ruby-example:latest
